# Generated by Django 5.1.7 on 2025-08-10 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='plan_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='modulo_pagos.planpagocolegiatura'),
        ),
    ]
