# Generated by Django 5.1.7 on 2025-08-10 19:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_certificados', '0002_initial'),
        ('modulo_estudiantes', '0001_initial'),
        ('modulo_pagos', '0002_matricula_plan_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_beca', models.CharField(help_text='Nombre de la beca (ej: Beca Excelencia, Beca Deportiva)', max_length=100)),
                ('tipo_beca', models.CharField(choices=[('porcentual', 'Porcentual'), ('monto_fijo', 'Monto Fijo'), ('combinada', 'Combinada')], default='porcentual', max_length=20)),
                ('porcentaje_descuento', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de descuento (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('monto_descuento', models.DecimalField(blank=True, decimal_places=2, help_text='Monto fijo de descuento', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('aplica_matricula', models.BooleanField(default=True, help_text='¿Aplica descuento a la matrícula?')),
                ('aplica_colegiatura', models.BooleanField(default=True, help_text='¿Aplica descuento a la colegiatura?')),
                ('aplica_certificado', models.BooleanField(default=False, help_text='¿Aplica descuento al certificado?')),
                ('fecha_inicio', models.DateField(help_text='Fecha desde cuando aplica la beca')),
                ('fecha_fin', models.DateField(help_text='Fecha hasta cuando aplica la beca')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('motivo', models.TextField(help_text='Motivo de la beca')),
                ('documentos_soporte', models.FileField(blank=True, null=True, upload_to='documentos_becas/')),
                ('aprobado_por', models.CharField(blank=True, help_text='Persona que aprobó la beca', max_length=100)),
                ('fecha_aprobacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='modulo_estudiantes.estudiante')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='modulo_certificados.evento')),
            ],
            options={
                'verbose_name': 'Beca',
                'verbose_name_plural': 'Becas',
                'unique_together': {('estudiante', 'evento', 'nombre_beca')},
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_descuento', models.CharField(help_text='Nombre del descuento', max_length=100)),
                ('tipo_descuento', models.CharField(choices=[('porcentual', 'Porcentual'), ('monto_fijo', 'Monto Fijo')], default='porcentual', max_length=20)),
                ('porcentaje_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('monto_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('aplica_matricula', models.BooleanField(default=True)),
                ('aplica_colegiatura', models.BooleanField(default=True)),
                ('aplica_certificado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('expirado', 'Expirado')], default='activo', max_length=20)),
                ('motivo', models.TextField(help_text='Motivo del descuento')),
                ('codigo_promocional', models.CharField(blank=True, help_text='Código promocional si aplica', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='modulo_estudiantes.estudiante')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='modulo_certificados.evento')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'unique_together': {('estudiante', 'evento', 'nombre_descuento')},
            },
        ),
    ]
