# Generated by Django 5.1.7 on 2025-08-10 20:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_certificados', '0002_initial'),
        ('modulo_estudiantes', '0001_initial'),
        ('modulo_pagos', '0003_beca_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPagoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plan', models.CharField(choices=[('cuotas_especiales', 'Cuotas Especiales'), ('plan_flexible', 'Plan Flexible'), ('convenio_institucional', 'Convenio Institucional'), ('otro', 'Otro')], default='cuotas_especiales', max_length=30)),
                ('numero_cuotas_personalizado', models.PositiveIntegerField(help_text='Número de cuotas personalizado para este estudiante', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('monto_matricula_personalizado', models.DecimalField(blank=True, decimal_places=2, help_text='Monto de matrícula personalizado (dejar vacío para usar el del evento)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_colegiatura_personalizado', models.DecimalField(blank=True, decimal_places=2, help_text='Monto de colegiatura personalizado (dejar vacío para usar el del evento)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('fecha_inicio', models.DateField(help_text='Fecha desde cuando aplica este plan')),
                ('fecha_fin', models.DateField(help_text='Fecha hasta cuando aplica este plan')),
                ('motivo', models.TextField(help_text='Motivo por el cual se aplica este plan personalizado')),
                ('aprobado_por', models.CharField(blank=True, help_text='Persona que aprobó el plan', max_length=100)),
                ('documentos_soporte', models.FileField(blank=True, null=True, upload_to='documentos_planes_personalizados/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_personalizados', to='modulo_estudiantes.estudiante')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_personalizados', to='modulo_certificados.evento')),
            ],
            options={
                'verbose_name': 'Plan de Pago Personalizado',
                'verbose_name_plural': 'Planes de Pago Personalizados',
                'unique_together': {('estudiante', 'evento')},
            },
        ),
    ]
