# Generated by Django 5.1.7 on 2025-08-10 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_pagos', '0004_planpagopersonalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpagopersonalizado',
            name='numero_cuotas_personalizado',
            field=models.PositiveIntegerField(help_text='Número de cuotas personalizado para este estudiante', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
