# Generated by Django 5.1.7 on 2025-08-10 20:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_pagos', '0005_alter_planpagopersonalizado_numero_cuotas_personalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpagopersonalizado',
            name='aplica_certificado',
            field=models.BooleanField(default=False, help_text='¿Aplica plan personalizado al certificado?'),
        ),
        migrations.AddField(
            model_name='planpagopersonalizado',
            name='aplica_colegiatura',
            field=models.BooleanField(default=True, help_text='¿Aplica plan personalizado a la colegiatura?'),
        ),
        migrations.AddField(
            model_name='planpagopersonalizado',
            name='aplica_matricula',
            field=models.BooleanField(default=True, help_text='¿Aplica plan personalizado a la matrícula?'),
        ),
        migrations.AddField(
            model_name='planpagopersonalizado',
            name='monto_certificado_personalizado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de certificado personalizado (dejar vacío para usar el del evento)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
