# Generated by Django 5.1.7 on 2025-08-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_pagos', '0006_planpagopersonalizado_aplica_certificado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planpagopersonalizado',
            name='aplica_certificado',
        ),
        migrations.RemoveField(
            model_name='planpagopersonalizado',
            name='aplica_colegiatura',
        ),
        migrations.RemoveField(
            model_name='planpagopersonalizado',
            name='aplica_matricula',
        ),
        migrations.RemoveField(
            model_name='planpagopersonalizado',
            name='monto_certificado_personalizado',
        ),
        migrations.RemoveField(
            model_name='planpagopersonalizado',
            name='monto_matricula_personalizado',
        ),
    ]
