# Generated by Django 5.1.7 on 2025-08-10 20:49

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_pagos', '0007_remove_planpagopersonalizado_aplica_certificado_and_more'),
    ]

    operations = [
        # Crear la tabla InstitucionFinanciera
        migrations.CreateModel(
            name='InstitucionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la institución', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la institución financiera', max_length=100)),
                ('tipo_institucion', models.CharField(choices=[('banco', 'Banco'), ('cooperativa', 'Cooperativa'), ('financiera', 'Financiera'), ('otro', 'Otro')], default='banco', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='¿La institución está activa?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institución Financiera',
                'verbose_name_plural': 'Instituciones Financieras',
                'ordering': ['nombre'],
            },
        ),
        
        # Agregar campos a la tabla Cuota
        migrations.AddField(
            model_name='cuota',
            name='plan_pago_colegiatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='modulo_pagos.planpagocolegiatura'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='plan_pago_personalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='modulo_pagos.planpagopersonalizado'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='institucion_financiera',
            field=models.ForeignKey(blank=True, help_text='Institución financiera donde se realizó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_pagos.institucionfinanciera'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='codigo_comprobante',
            field=models.CharField(blank=True, help_text='Código de comprobante de la institución financiera', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        
        # Crear la tabla PagoCuota
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, help_text='Monto pagado en esta transacción', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha_pago', models.DateField(help_text='Fecha en que se realizó el pago')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta de Crédito'), ('cheque', 'Cheque'), ('deposito', 'Depósito'), ('pago_movil', 'Pago Móvil')], max_length=20)),
                ('codigo_comprobante', models.CharField(blank=True, help_text='Código de comprobante de la institución financiera', max_length=50, null=True)),
                ('comprobante', models.ImageField(blank=True, help_text='Imagen del comprobante de pago', null=True, upload_to='comprobantes_pago_cuotas/')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del pago')),
                ('numero_transaccion', models.CharField(blank=True, help_text='Número de transacción interno o de la institución', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_cuota', to='modulo_pagos.cuota')),
                ('institucion_financiera', models.ForeignKey(blank=True, help_text='Institución financiera donde se realizó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_pagos.institucionfinanciera')),
            ],
            options={
                'verbose_name': 'Pago de Cuota',
                'verbose_name_plural': 'Pagos de Cuotas',
                'ordering': ['-fecha_pago', '-fecha_creacion'],
            },
        ),
        
        # Actualizar las opciones del modelo Cuota
        migrations.AlterModelOptions(
            name='cuota',
            options={'verbose_name': 'Cuota', 'verbose_name_plural': 'Cuotas'},
        ),
        
        # Agregar unique_together para Cuota
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('plan_pago_colegiatura', 'numero_cuota'), ('plan_pago_personalizado', 'numero_cuota')},
        ),
        
        # Remover el campo plan_pago antiguo
        migrations.RemoveField(
            model_name='cuota',
            name='plan_pago',
        ),
    ]
