# Generated by Django 5.1.7 on 2025-08-12 00:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_pagos", "0009_fix_database_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="monto_aplicado_colegiatura",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monto aplicado específicamente a colegiatura (para pagos parciales/totales)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="tipo_pago",
            field=models.CharField(
                choices=[
                    ("matricula", "Matrícula"),
                    ("cuota_individual", "Cuota Individual"),
                    ("colegiatura_parcial", "Colegiatura Parcial"),
                    ("colegiatura_total", "Colegiatura Total"),
                    ("certificado", "Certificado"),
                    ("miscelaneo", "Misceláneo"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="pagocuota",
            name="monto_pagado",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monto pagado en esta transacción",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.CreateModel(
            name="PagoCuotaAplicada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto_aplicado",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto específico aplicado a esta cuota desde este pago",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("fecha_aplicacion", models.DateTimeField(auto_now_add=True)),
                (
                    "cuota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_aplicados_detalle",
                        to="modulo_pagos.cuota",
                    ),
                ),
                (
                    "pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicaciones_cuotas",
                        to="modulo_pagos.pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aplicación de Pago a Cuota",
                "verbose_name_plural": "Aplicaciones de Pago a Cuotas",
                "unique_together": {("pago", "cuota")},
            },
        ),
        migrations.AddField(
            model_name="pago",
            name="cuotas_aplicadas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Cuotas a las que se aplica este pago (para pagos parciales/totales)",
                related_name="pagos_aplicados",
                through="modulo_pagos.PagoCuotaAplicada",
                to="modulo_pagos.cuota",
            ),
        ),
    ]
