# Generated by Django 5.1.7 on 2025-08-12 11:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_pagos", "0011_unificar_planes_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planpago",
            name="monto_colegiatura",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monto total de la colegiatura a prorratear en cuotas",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="planpago",
            name="numero_cuotas",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(60),
                ]
            ),
        ),
    ]
