# Generated by Django 5.1.7 on 2025-08-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_pagos", "0012_alter_planpago_monto_colegiatura_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matricula",
            name="comprobante_matricula",
            field=models.FileField(
                blank=True,
                help_text="Comprobante de matrícula del estudiante",
                null=True,
                upload_to="comprobantes_matricula/",
            ),
        ),
        migrations.AddField(
            model_name="planpago",
            name="constancia_convenio",
            field=models.FileField(
                blank=True,
                help_text="Documento de constancia del convenio de pago",
                null=True,
                upload_to="convenios_pago/",
            ),
        ),
        migrations.AddField(
            model_name="planpago",
            name="motivo_convenio",
            field=models.TextField(blank=True, help_text="Motivo del convenio de pago"),
        ),
        migrations.AddField(
            model_name="planpago",
            name="tiene_convenio",
            field=models.BooleanField(
                default=False, help_text="Indica si tiene un convenio de pago especial"
            ),
        ),
    ]
