# Generated by Django 5.1.7 on 2025-08-10 18:35

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo_certificado', models.CharField(blank=True, max_length=50, unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GENERADO', 'Generado'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_estudiantes/')),
                ('qr', models.ImageField(blank=True, null=True, upload_to='qr_certificados/')),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CostoMiscelaneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('es_obligatorio', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('diploma', 'Diploma'), ('vinculacion', 'Vinculación'), ('simposio', 'Simposio'), ('conversatorio', 'Conversatorio')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('lugar', models.CharField(blank=True, max_length=150)),
                ('codigo_evento', models.CharField(default='TEMP_EVT', max_length=20, unique=True)),
                ('aval', models.CharField(blank=True, default='UTEQ', max_length=20)),
                ('horas_academicas', models.IntegerField(default=20)),
                ('plantilla', models.ImageField(blank=True, null=True, upload_to='plantillas/')),
                ('costo_matricula', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('costo_colegiatura', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('costo_certificado', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('numero_maximo_cuotas', models.PositiveIntegerField(default=8, validators=[django.core.validators.MaxValueValidator(8)])),
                ('requiere_matricula', models.BooleanField(default=True)),
                ('permite_pago_certificado_anticipado', models.BooleanField(default=True)),
            ],
        ),
    ]
