# Generated by Django 5.1.7 on 2025-08-10 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_certificados', '0001_initial'),
        ('modulo_estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='costomiscelaneo',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_miscelaneos', to='modulo_certificados.evento'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_certificados.evento'),
        ),
    ]
