name: CI/CD Pipeline (disabled)

# Deshabilitado para evitar duplicidad con ci.yml
on:
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  DJANGO_VERSION: '5.1.7'

jobs:
  noop:
    name: Deshabilitado
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow deshabilitado. Usar .github/workflows/ci.yml"
